version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /home/maczech/home-assistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
  mqtt:
    image: eclipse-mosquitto:2.0
    restart: unless-stopped
    volumes:
        - "./mosquitto-data:/mosquitto"
    command: "mosquitto -c /mosquitto-no-auth.conf"
      #network_mode: host
    ports:
      - "1883:1883"
      - "9001:9001"
  zigbee2mqtt:
    container_name: zigbee2mqtt
    restart: unless-stopped
    image: koenkk/zigbee2mqtt
    volumes:
      - ./zigbee2mqtt-data:/app/data
      - /run/udev:/run/udev:ro
    environment:
      - TZ=Europe/Warsaw
    devices:
      - /dev/ttyACM0:/dev/ttyUSB0
        #group_add:
        #- dialout
        #user: 1000:1000
      #network_mode: host
    ports:
      - 8080:8080
    environment:
      - TZ=Europe/Warsaw
